### ISSUE TITLE
bug 有点多啊

### ISSUE THREAD

**Issue by renmada** [strawberryx/CoFEE#2]
在Stage1: ESI出现了至少10次

希望能再调试一下

**Comment by berryxue** [comment]
您好，请问是什么错误呢，我这里可以正常跑通

**Comment by renmada** [comment]
比如最简单的拼写错误

我刚重新下了从github下了代码， 运行Stage1，就报错这个错(具体看图)。类似的错误还有很多啊。
传上来的代码版本不对？
<img width="369" alt="企业微信截图_20210104140202" src="https://user-images.githubusercontent.com/43545086/103505666-ca88f900-4e95-11eb-8f09-42561c066fcf.png">

**Comment by berryxue** [comment]
I have updated the code and readme.md, thanks for your suggestion
