### ISSUE TITLE
unable to process data from wikipedia

### ISSUE THREAD

**Issue by ZooLulu** [strawberryx/CoFEE#3]
Hello, write_tag.py file can't process the data from wikipedia

**Comment by berryxue** [comment]
Which version do you dump and what is the error message?

**Comment by ZooLulu** [comment]
I download the latest version of Wikipedia.
The problem is that the _write_tag.py_ file does not import any dependent libraries and there are some undefined functions and variables.
` line = ff(line, interlinks_index[j])`
like the ff() function above

**Comment by berryxue** [comment]
Im sorry for that! Now I have updated it.
